# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true # 访问路径可以显示IP地址
    instance-id: ${spring.application.name} # 服务别名代替Ip名（别名）
  client:
    service-url:
      defaultZone: http://mask:mask@localhost:8761/eureka/
