eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 4000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    renewal-percent-threshold: 0.9